# EMBEDDED SERVER CONFIGURATION
server:
  port: ${port:18080}
  error.whitelabel.enabled: false
  use-forward-headers: true

  compression:
    enabled: true
    min-response-size: 1024
    mime-types:
      - text/html
      - text/css
      - text/plain
      - text/xml
      - application/json
      - application/javascript
  servlet:
    context-path: /

# PROFILES
spring:
  application.name: dapo-website

  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB

# RabbitMQ datasource
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
    dynamic: true

  thymeleaf:
    prefix: classpath:/templates

# ZULL
zuul:
  add-proxy-headers: true
  add-host-header: true
  host:
    connect-timeout-millis: 8000
    socket-timeout-millis: 10000
  routes:
    dapo-api:
      sensitiveHeaders:
      path: /api/**
      stripPrefix: false
    dapo-authserver:
      sensitiveHeaders:
      path: /auth/**
      serviceId: dapo-authserver
      stripPrefix: false
    dapo-authserver-oath2:
      sensitiveHeaders:
      path: /oauth2/**
      serviceId: dapo-authserver
      stripPrefix: false
    dapo-authserver-user:
      sensitiveHeaders:
      path: /user/**
      serviceId: dapo-authserver
      stripPrefix: false

# Fix the error upon first load
ribbon:
  eager-load.enabled: true

# EUREKA
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKAHOST:localhost}:${EUREKAPORT:18761}/eureka/

---

# Use this profile fi you start this application trought the IDEA
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKAHOST:localhost}:${EUREKAPORT:18761}/eureka/

---

spring:
  profiles: ssl
server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:dapo.p12
    key-store-password: 123456-Aa