server:
  port: ${port:8081}
  error.whitelabel.enabled: false
  compression:
    enabled: true
    min-response-size: 102400000
    mime-types:
      - text/html
      - text/css
      - text/plain
      - text/xml
      - application/json
      - application/javascript
  servlet:
    context-path: /api/v1

spring:
  application.name: dapo-api
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DBHOST:localhost}:5432/${DBNAME:dapo}
    username: ${DBUSER:dapo}
    password: ${DBPASS:dapo}
    driverClassName: org.postgresql.Driver