version: "3.7"

networks:
  dapo_bridge:

services:

  dapo-db-postgis:
    image: kartoza/postgis
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dapo
      - POSTGRES_PASS=dapo
      - POSTGRES_DBNAME=dapo
    networks:
      - dapo_bridge

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dapo
    networks:
      - dapo_bridge

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9001:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: dapo
    networks:
      - dapo_bridge

  dapo-authserver:
    image: dapo/dapo-authserver
    networks:
      - dapo_bridge
    ports:
     - 8082:8082
    depends_on:
     - dapo-db-postgis
     - dapo-discovery

  dapo-api:
    image: dapo/dapo-api
    ports:
     - 8081:8081
    networks:
      - dapo_bridge
    depends_on:
     - dapo-db-postgis
     - dapo-discovery

  dapo-discovery:
    image: dapo/dapo-eureka
    networks:
      - dapo_bridge
    ports:
     - 8761:8761
