version: "3.7"

networks:
  dapo_bridge:

services:

  dapo-db-postgis:
    image: kartoza/postgis
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dapo
      - POSTGRES_PASS=dapo
      - POSTGRES_DBNAME=dapo
    networks:
      - dapo_bridge